### ISSUE TITLE
Consider adding to vertx-awesome

### ISSUE THREAD

**Issue by vietj** [wem/vertx-dart-sockjs#1]
Hi,

we maintain a vertx-awesome list of vertx related project in the community.

it would be great to add vertx-dart-sockjs to the list

https://github.com/vert-x3/vertx-awesome

**Comment by michel-kraemer** [comment]
Done. Thanks.

**Comment by wem** [comment]
Perfect ... thx u too

**Comment by vietj** [comment]
awesome great!
